### ISSUE TITLE
execfile() vs. run

### ISSUE THREAD

**Issue by teuben** [teuben/dc2019#11]
Here we like to contrast running scripts in two ways:
     execfile('script.py")
and
     run script.py --foo 1.0   -bar  a.fits
which would make scripting a lot more flexible, allowing parameters (QAC does that by default).

The problem is that the run version does not know about casa anymore. In CASA6 this is less of a problem, but still needs to be set up before you can use casa tasks and tools.

A cop out for the paper is to have all scripts hard coded, but it would be nice to have an environment that can be parameterized more easily.

**Comment by dpetry** [comment]
The execfile way is what ALMA users are familiar with.
The ALMA calibration and imaging scripts work this way.
For sdintimaging, I wrote a script containing a function, i.e. you either import or execfile it
and then run the function (e.g. runsdintimg() ) as often as you want and *with parameters*.

The "run" way restarts CASA for each run. I find that inefficient.

**Comment by teuben** [comment]
This is how QAC was done. I collect all my useful things via an execfile or using  sys.path.append(), then magically these new functions are available.  I was hoping there would be a better way of doing it in casa6.   I'm worried, since execfile() is a hack where they import the global and local variables, that any local hack (such as QAC) would then not work with the execfile hack. The proof will be in the pudding, but it's bound  to break at some point since it's not a python3 feature.

**Comment by dpetry** [comment]
The analysis scripts are not a "library" which you would load from the sys.path.
But something like runsdintimg is of general use. And so it was put into an importable py file
which you could place into the sys.path as you suggest.
So, I would say, use python functions and modules for things of general use which can have parameters.
And use directly executable scripts via execfile for specific hard-wired analysis scripts without parameters.

**Comment by bmason72** [comment]
I am most familiar with execfile(), and for no good reason resist giving it
up. With python3 I believe we will all have to, unless we define a similar
replacement function (?).  One thing i've read but don't have a lot of
experience with is that the debug information you get from some of the
straightforward replacement options are not as good as execfile()

**Comment by dpetry** [comment]
execfile() was preserved in CASA 6! (At my and  a few other people's strong intervention.)
You can continue to use it!
