### ISSUE TITLE
Ticket to track redundancies in datacomb.py and DC_script.py

### ISSUE THREAD

**Issue by adeleplunkett** [teuben/dc2019#17]
As of April 2021, the wrapper script datacomb.py can be tested, together with DC_script.py.  The various combinations teams will run these scripts, with additional iterations, in order to test that the output combined images are as expected.

If anyone finds redundancies in the script (i.e. rms calculated several times in different methods), please document them here.  Then we can coordinate in order to minimize unnecessary redundancies.

**Comment by adeleplunkett** [comment]
In DC_script.py: imbase and sdbase are each assigned, but appear to be the same string.

**Comment by adeleplunkett** [comment]
DC_script.py:
Need to check on this: 
```
startchan = 30 #None
endchan = 39 #None 
```
This should be None automatically in case of mfs, and should only be required for cube.

**Comment by adeleplunkett** [comment]
DC_script.py:
`dryrun=True`
does not seem to have the expected effect in most recent version. In my case, it did the concat, and generated *.mask and *.template.* files.  I think this was related to some preparatory TCLEAN step. The actually combination did not happen.

**Comment by teuben** [comment]
We need some clarification on the workflow.    datacomb.py are our functions, but without sys.path.append() they are painful to use. So where should this sys.path.append() happen.   In DC_script.py it is hardcoded,but even with a configure (see #18 ) step there is still a catch-22 when you are not in the scripts4paper directory.   Should we do something like what QAC does: add a magic load line to the casa init.py/startup.py file?

**Comment by LydiaMF** [comment]
> DC_script.py:
> Need to check on this:
> 
> ```
> startchan = 30 #None
> endchan = 39 #None 
> ```
> 
> This should be None automatically in case of mfs, and should only be required for cube.

If mode='mfs, the chan-parameteres above are ignored (aka "None"). But yes, we can set them to None in the cont data examples to avoid confusion.

**Comment by LydiaMF** [comment]
> DC_script.py:
> `dryrun=True`
> does not seem to have the expected effect in most recent version. In my case, it did the concat, and generated *.mask and _.template._ files. I think this was related to some preparatory TCLEAN step. The actually combination did not happen.

dryrun is used to collect the resulting file names for each of the selected steps without having to re-run the whole combination process. The collected names are to be fed into the assessment part.

**Comment by LydiaMF** [comment]
> In DC_script.py: imbase and sdbase are each assigned, but appear to be the same string.

True, wanted to leave the option open to give them an own name if the products folder gets too messy - I have not used this option myself for now. That's why they are the same at the moment and I think it can stay like that: sdbase=imbase.
