### ISSUE TITLE
Confusing Inputs for User

### ISSUE THREAD

**Issue by emoravec** [teuben/dc2019#19]
It is unclear to me what the user defined parameters are in DC_script.py.

In particular, I have deduced from the script and DC_script.md that I need to change `datacombpath`, `TP2WISpath`, `pathtoconcat`, and `pathtoimage`. But it is confusing where to put the names of the MSs that will be combined. In the current version of the script that I downloaded (on 9.4.21), there are a lot of commented out lines around where ‘thevis’  which is rather confusing. It seems to me that I need to edit `thevis` but that is not listed as a variable that needs input from the user in DC_script.md (though I found a reference to `thevis` at the end of DC_script.md but the text makes it seem as if this is an as needed basis but I think you need `thevis` no matter what?). I know I need to put the MSs somewhere and I am assuming `thevis` is it, is this true? 

As an aside, as a new user I am confused between `vis` listed in the DC_script.md and `thevis` in the script DC_script.py currently above `vis`. They seem to be different things but are named as if they are the same.

I might suggest making a separate file that contains all the user inputs and a description of what each is to make it clear these particular variables are the user defined inputs. And thus a consequent .md file describing only and specifically the inputs in more detail. Right now the inputs are a bit buried in the DC_script.md file.

Additionally, an example for a particular dataset would be extremely useful.

**Comment by teuben** [comment]
All these are related to the two other issues: #17 and #18 , and the question of the workflow. How do users use this. Which is not yet in the DC_scripts.md file.  One example of use would be if somebody else has installed this script4paper somewhere , and you want to use it, but obviously cannot write in their directory. How do you use it then?

**Comment by emoravec** [comment]
This issue was resolved by adding DC_run.py, DC_locals.py, and configure steps.
