### ISSUE TITLE
turbustat install for feather not working?

### ISSUE THREAD

**Issue by teuben** [teuben/dc2019#5]
After pip installing the following packages:

image_registration radio_beam reproject spectral_cube turbustat sklearn statsmodels scikit-image

the line
     import turbustat.simulator
will fail with "from .spectrum import generate_spectrum"

**Comment by teuben** [comment]
I should add that I used the miniconda3 install.

**Comment by teuben** [comment]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-0aec0b1c876a> in <module>()
----> 1 from turbustat.simulator.gen_field import make_extended

~/CASA/dc2019/contrib/miniconda3/lib/python3.6/site-packages/turbustat/simulator/__init__.py in <module>()
      1 
      2 from .gen_field import make_3dfield, make_extended
----> 3 from .make_cube import make_ppv

~/CASA/dc2019/contrib/miniconda3/lib/python3.6/site-packages/turbustat/simulator/make_cube.py in <module>()
     10 
     11 from ..io.sim_tools import create_cube_header
---> 12 from .spectrum import generate_spectrum
     13 
     14 SQRT_2PI = np.sqrt(2 * np.pi)

ModuleNotFoundError: No module named 'turbustat.simulator.spectrum'

**Comment by e-koch** [comment]
This ended up being an issue in the distribution on pypi. I've added a fixed version that can be installed with `pip install turbustat==1.1`.
